# === _config.yml ---------------------------------------------------------===
# Copyright Â© 2012 by its contributors (see AUTHORS for details). Distributed
# under the Creative Commons Attribution-ShareAlike 3.0 Unported License, the
# contents of which may be found in the accompanying file LICENSE or from the
# web address http://creativecommons.org/licenses/by-sa/3.0/deed.en_US.
# ===----------------------------------------------------------------------===

title : Freicoin
tagline: peer-to-peer demurrage currency
author :
    name: Freicoin Developers
    #email: freicoin@monetize.io
    #url: http://monetize.io/

theme: spacelab
favicon: /static/images/favicon.ico
apple_touch_icon: /static/images/apple-touch-icon.png

logo:
    header:
        src: '/static/images/logo-header.png'
    footer:
        src: '/static/images/logo-footer.png'

menu:
    primary:
        -
            title: Home
            url: /index.html
        -
            title: About
            url: /about/index.html
        -
            title: Download
            url: /download/index.html
        -
            title: Develop
            url: https://github.com/freicoin/freicoin
        -
            title: Discuss
            url: http://www.freicoin.org/
    footer:
        -
            title: About
            url: /about/index.html
        -
            title: Github
            url: https://github.com/freicoin/freicoin
        -
            title: Copyright
            url: /copyright/index.html

freicoin:
    version: 0.0.1-3
    release_date: 2012-12-28T16:45:00
    downloads:
        -
            name: Windows (exe)
            osid: Win
            icon: /static/images/os/win.png
            link: https://s3.amazonaws.com/in.freico.stable/freicoin-0.0.1-3-windows-setup.exe
            size: ~11MB
        -
            name: Windows (zip)
            icon: /static/images/os/win.png
            link: https://s3.amazonaws.com/in.freico.stable/freicoin-0.0.1-3-windows.zip
            size: ~14MB
        -
            name: Mac OS X
            osid: Mac
            icon: /static/images/os/mac.png
            link: https://s3.amazonaws.com/in.freico.stable/freicoin-0.0.1-3-macosx.dmg
            size: ~15MB
        -
            name: Linux
            osid: Linux
            icon: /static/images/os/linux.png
            link: https://s3.amazonaws.com/in.freico.stable/freicoin-0.0.1-3-linux.tar.xz
            size: ~17MB
        -
            name: Source
            osid: Unknown
            icon: /static/images/os/src.png
            link: https://github.com/freicoin/freicoin/archive/v0.0.1-3.zip
            size: ~2MB

analytics:
    google:
        code: UA-35675637-1

exclude:
    - ".cache"
    - ".pkg"
    - ".rbenv-version"
    - "AUTHORS"
    - "CNAME"
    - "Gemfile"
    - "Gemfile.lock"
    - "LICENSE"
    - "Makefile"
    - "Makefile.local"
    - "README.md"
    - "changelog.md"
    - "configure"
auto: true
pygments: true

# ===----------------------------------------------------------------------===
# End of File
# ===----------------------------------------------------------------------===
